### ISSUE TITLE
Google Place New API Migration requests

### ISSUE THREAD

**Issue by maulikchak** [Shrutimahajan/Google-AutoComplete-TextField-Flutter#74]
Hi, thanks for this great package!

Google has released a new Places API (v1) that replaces the old autocomplete endpoint:
https://places.googleapis.com/v1/places:autocomplete

The current version of this package still uses the legacy endpoint, which is being deprecated.

Can you please update the package to support the new API? It uses POST requests with JSON and requires the API key to be sent in headers.

Let me know if I can help or test it. Thanks again!

[About the Places API (New)](https://developers.google.com/maps/documentation/places/web-service/op-overview)
[Autocomplete (New) and session tokens](https://developers.google.com/maps/documentation/places/web-service/place-autocomplete)

**Comment by MTsung** [comment]
@maulikchak 

I opened a PR #78 that integrates the new Google Places API.  

- adds a `useNewApi` flag to toggle between the new and legacy APIs.  
- To avoid affecting existing users, the flag defaults to `false`.


Before the PR is merged, you can try out the new functionality by pointing to this branch:

```yaml
  google_places_flutter: 
    git:
      url: https://github.com/MTsung/Google-AutoComplete-TextField-Flutter.git
      ref: 2c7ac5873fdbfd3e83ec303861fe3618349bd17f
```

If you encounter any issues, feel free to leave a comment on the PR, and I will address them.
